# Generated by Django 5.2.4 on 2025-09-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
    ]
